# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    # Raise pull requests for version updates on `master` branch
    target-branch: "master"
    schedule:
      interval: "daily"
      # Check for npm updates at 0815hrs UTC
      time: "08:15"
    reviewers:
       - "TweetWallFX/tweetwallfx-admins"
    # Allow up to N open pull requests (independant of source)
    open-pull-requests-limit: 50

  - package-ecosystem: "gradle"
    # Any gradle based dependencies
    directories:
      - "/"
      - "/2d"
      - "/3d"
      - "/cache"
      - "/conference-api"
      - "/conference-spi"
      - "/conference-stepengine"
      - "/conference-test"
      - "/config"
      - "/controls"
      - "/core"
      - "/emoji"
      - "/filterchain"
      - "/generic2d"
      - "/google-cloud"
      - "/mqtt"
      - "/stepengine-api"
      - "/stepengine-dataproviders"
      - "/stepengine-steps"
      - "/transitions"
      - "/tweet-api"
      - "/tweet-impl-mastodon4j"
      - "/tweet-impl-mock"
      - "/tweet-impl-twitter4j"
      - "/util"
    # Raise pull requests for version updates on `master` branch
    target-branch: "master"
    schedule:
      interval: "daily"
      # Check for npm updates at 0815hrs UTC
      time: "08:15"
    reviewers:
       - "TweetWallFX/tweetwallfx-admins"
    # Group Update PRs
    groups:
      javafx:
        patterns:
          - "org.openjfx:javafx-*"
    # Allow up to N open pull requests (independant of source)
    open-pull-requests-limit: 50
